"""create factory table

Revision ID: 6536806ba68e
Revises: 
Create Date: 2026-05-19 10:12:44.890804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6536806ba68e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deployment_type', sa.Enum('ON_PREM', 'PRIVATE_CLOUD', name='deploymenttype'), nullable=False),
    sa.Column('langfuse_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('langfuse_project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('kpi_targets', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_name'), 'factory', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factory_name'), table_name='factory')
    op.drop_table('factory')
    # ### end Alembic commands ###
