"""create anomaly_signal rca_finding regression_run tables

Revision ID: f5c1cd0e5cf6
Revises: ebc704559248
Create Date: 2026-05-19 10:36:44.259909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5c1cd0e5cf6'
down_revision: Union[str, Sequence[str], None] = 'ebc704559248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_signal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('METRIC_DRIFT', 'COST_SPIKE', 'HUMAN_FLAG', 'SCHEDULED', name='anomalysourcetype'), nullable=False),
    sa.Column('related_trace_refs', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ANALYZING', 'RESOLVED', 'DISMISSED', name='anomalystatus'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_signal_agent_id'), 'anomaly_signal', ['agent_id'], unique=False)
    op.create_table('regression_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('skill_id_old', sa.Uuid(), nullable=False),
    sa.Column('skill_id_new', sa.Uuid(), nullable=False),
    sa.Column('test_set_strategy', sa.Enum('REPLAY_RECENT', 'GOLDEN', 'MIXED', name='testsetstrategy'), nullable=False),
    sa.Column('test_case_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('per_case_results', sa.JSON(), nullable=True),
    sa.Column('regression_findings', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.Enum('PASS', 'FAIL', 'NEEDS_REVIEW', name='regressionverdict'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id_new'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['skill_id_old'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_run_skill_id_new'), 'regression_run', ['skill_id_new'], unique=False)
    op.create_index(op.f('ix_regression_run_skill_id_old'), 'regression_run', ['skill_id_old'], unique=False)
    op.create_table('rca_finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('anomaly_signal_id', sa.Uuid(), nullable=False),
    sa.Column('root_cause_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('suggested_fix_type', sa.Enum('PROMPT_CHANGE', 'ADD_SKILL', 'SUPPLEMENT_SOP', 'SWAP_MODEL', 'RETRAINING', name='suggestedfixtype'), nullable=False),
    sa.Column('suggested_fix_payload', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', 'AUTO_APPLIED', name='rcafindingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_signal_id'], ['anomaly_signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_finding_anomaly_signal_id'), 'rca_finding', ['anomaly_signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rca_finding_anomaly_signal_id'), table_name='rca_finding')
    op.drop_table('rca_finding')
    op.drop_index(op.f('ix_regression_run_skill_id_old'), table_name='regression_run')
    op.drop_index(op.f('ix_regression_run_skill_id_new'), table_name='regression_run')
    op.drop_table('regression_run')
    op.drop_index(op.f('ix_anomaly_signal_agent_id'), table_name='anomaly_signal')
    op.drop_table('anomaly_signal')
    op.execute("DROP TYPE IF EXISTS anomalysourcetype")
    op.execute("DROP TYPE IF EXISTS anomalystatus")
    op.execute("DROP TYPE IF EXISTS rcafindingstatus")
    op.execute("DROP TYPE IF EXISTS suggestedfixtype")
    op.execute("DROP TYPE IF EXISTS testsetstrategy")
    op.execute("DROP TYPE IF EXISTS regressionverdict")
    # ### end Alembic commands ###
