"""POST /portfolio-generations — flows2agents portfolio mode + DB persistence."""
from __future__ import annotations

from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from flows2agents.ir import SkillIR
from flows2agents.llm.base import LLMProvider
from pydantic import BaseModel
from sqlmodel import Session, select

from agentops_core.database import get_provider, get_session, get_storage
from agentops_core.models.agent import Agent, RuntimeStatus
from agentops_core.models.factory import Factory
from agentops_core.models.skill import Skill, SkillStatus
from agentops_core.models.sop_source import SOPSource
from agentops_core.services.flows2agents_service import generate_portfolio
from agentops_core.services.skill_mapper import skill_ir_to_skill_payload
from agentops_core.services.storage import LocalStorage

router = APIRouter(prefix="/portfolio-generations", tags=["portfolio_generation"])


class PortfolioGenerationRequest(BaseModel):
    factory_id: UUID
    sop_source_ids: list[UUID]
    description: str


class PortfolioAgentResult(BaseModel):
    id: UUID
    name: str
    purpose: str
    skill_ids: list[UUID]


class PortfolioGenerationResponse(BaseModel):
    run_id: str
    agents: list[PortfolioAgentResult]


@router.post(
    "",
    response_model=PortfolioGenerationResponse,
    status_code=status.HTTP_201_CREATED,
)
def create_portfolio_generation(
    payload: PortfolioGenerationRequest,
    session: Session = Depends(get_session),
    storage: LocalStorage = Depends(get_storage),
    provider: LLMProvider = Depends(get_provider),
) -> PortfolioGenerationResponse:
    factory = session.get(Factory, payload.factory_id)
    if factory is None:
        raise HTTPException(status_code=404, detail="Factory not found")

    sops = list(
        session.exec(
            select(SOPSource).where(SOPSource.id.in_(payload.sop_source_ids))
        ).all()
    )
    if len(sops) != len(payload.sop_source_ids):
        raise HTTPException(status_code=404, detail="One or more SOP sources not found")

    result = generate_portfolio(
        factory_description=payload.description,
        sop_sources=sops,
        storage=storage,
        provider=provider,
    )

    # Group built_skills by agent_name → create Agent + Skills
    by_agent: dict[str, list[dict[str, Any]]] = {}
    for entry in result["built_skills"]:
        by_agent.setdefault(entry["agent_name"], []).append(entry)

    sop_set_id = f"portfolio-{result['run_id']}"
    agents_resp: list[PortfolioAgentResult] = []

    for agent_name, entries in by_agent.items():
        first = entries[0]
        agent = Agent(
            factory_id=factory.id,
            name=agent_name,
            purpose=(
                f"{first.get('agent_role', '')} — "
                f"Auto-generated by portfolio run {result['run_id']}"
            ),
            runtime_status=RuntimeStatus.PENDING,
        )
        session.add(agent)
        session.commit()
        session.refresh(agent)

        skill_ids: list[UUID] = []
        for version_idx, entry in enumerate(entries, start=1):
            skill_ir = SkillIR.model_validate(entry["skill_ir"])
            mapped = skill_ir_to_skill_payload(skill_ir)
            skill = Skill(
                agent_id=agent.id,
                version=version_idx,
                status=SkillStatus.DRAFT,
                prompt=mapped["prompt"],
                tool_specs=mapped["tool_specs"],
                golden_test_cases=mapped["golden_test_cases"],
                sop_source_set_id=sop_set_id,
                generated_by_run_id=f"{result['run_id']}/{entry['skill_name']}",
            )
            session.add(skill)
            session.commit()
            session.refresh(skill)
            skill_ids.append(skill.id)

        agents_resp.append(
            PortfolioAgentResult(
                id=agent.id,
                name=agent.name,
                purpose=agent.purpose,
                skill_ids=skill_ids,
            )
        )

    return PortfolioGenerationResponse(run_id=result["run_id"], agents=agents_resp)
